str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
str_sims.py:99: RuntimeWarning: invalid value encountered in divide
  fits=fits/(sum(fits))
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.1.0_mu_0.0005_fit_0.1'
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.0.9_mu_0.0005_fit_0.1'
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.0.8_mu_0.0005_fit_0.1'
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.0.7_mu_0.0005_fit_0.1'
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.0.6_mu_0.0005_fit_0.1'
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.0.5_mu_0.0005_fit_0.1'
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.0.4_mu_0.0005_fit_0.1'
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.0.2_mu_0.0005_fit_0.1'
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.0.3_mu_0.0005_fit_0.1'
Traceback (most recent call last):
  File "str_sims.py", line 390, in <module>
    path=args.p)
  File "str_sims.py", line 295, in main
    f_g=open(fname_genotypes, 'w')
IOError: [Errno 2] No such file or directory: '/home/eglassbe/str_simulations/str_res/run_9/genos_SNP.0.1_mu_0.0005_fit_0.1'
